# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

# Inspired on https://github.com/juliasilge/tidytext
environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    USE_RTOOLS: true
  matrix:
    - INSTALL_PIP: false
      INSTALL_MHCNUGGETS: false
    - INSTALL_PIP: true
      INSTALL_MHCNUGGETS: false
    - INSTALL_PIP: true
      INSTALL_MHCNUGGETS: true

build_script:
  - travis-tool.sh install_deps

test_script:
  #- sh: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then ./scripts/install_mhcnuggets.sh; fi
  - ps: if ($INSTALL_PIP -eq "true") {echo "YAY! Installing pip"}
  - ps: if ($INSTALL_PIP) {echo "Installing pip"}
  - ps: if ($INSTALL_PIP -eq "true") {./scripts/install_pip.sh}
  - ps: if ($INSTALL_PIP) {./scripts/install_pip.sh}
  - ps: if ($INSTALL_MHCNUGGETS) {echo "Installing MHCnuggets"}
  - ps: if ($INSTALL_MHCNUGGETS -eq "true") {echo "YAY! Installing MHCnuggets"}
  - ps: if ($INSTALL_MHCNUGGETS) {./scripts/install_mhcnuggets.sh}
  - ps: if ($INSTALL_MHCNUGGETS -eq "true") {./scripts/install_mhcnuggets.sh}
  #- travis-tool.sh run_tests
  #- Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
