language: r
dist: bionic
cache: packages

matrix:
  jobs:
  - r: devel
    os: linux
    env: INSTALL_MHCNUGGETS=false INSTALL_PIP=false
  - r: release
    os: linux
    env: INSTALL_MHCNUGGETS=false INSTALL_PIP=true
  - r: devel
    os: linux
    env: INSTALL_MHCNUGGETS=true INSTALL_PIP=true
  #- r: release
  #  os: osx
  #  env: INSTALL_MHCNUGGETS=true INSTALL_PIP=true

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

before_script:
  - if [[ "$INSTALL_PIP" == true ]]; then sudo apt install python3-pip; fi
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then ./scripts/install_mhcnuggets.sh; fi

after_success:
  - if [[ "$INSTALL_MHCNUGGETS" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'goodpractice::gp()'; fi
  - # No local files created
  - # if [[ $(egrep -R "\"~" --include={*.R,*.Rmd} | egrep -v README.Rmd) ]]; then echo "Local file created"; exit 1; fi;
  - Rscript -e 'install.packages(".", repos = NULL, type = "source")'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_self_test()'

after_failure:
  - ls
  - Rscript -e 'install.packages(".", repos = NULL, type = "source")'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_self_test()'


