language: r
dist: bionic
cache: packages

env:
  - INSTALL_MHCNUGGETS=true
  - INSTALL_MHCNUGGETS=false

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

before_script:
  - sudo apt install python3-pip
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then ./scripts/install_mhcnuggets.sh; fi

after_success:
  - if [[ "$INSTALL_MHCNUGGETS" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'goodpractice::gp()'; fi
  - # No local files created
  - # if [[ $(egrep -R "\"~" --include={*.R,*.Rmd} | egrep -v README.Rmd) ]]; then echo "Local file created"; exit 1; fi;
  - Rscript -e 'install.packages(".", repos = NULL, type = "source")'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_self_test()'

after_failure:
  - ls
  - Rscript -e 'install.packages(".", repos = NULL, type = "source")'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_self_test()'


